services:

  rl-course:

    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: rl-course

    volumes:
      - .:/workspace

    working_dir: /workspace

    stdin_open: true

    tty: true
